# SPDX-FileCopyrightText: © 2024-2026 decompals
# SPDX-License-Identifier: MIT

[package]
name = "slinky-cli"
version = "0.6.0"
edition = "2021"
rust-version = "1.74"
authors = ["Anghelo Carvajal <angheloalf95@gmail.com>"]
license = "MIT"
description = "Linker script generator for decompilation and modding projects"
repository = "https://github.com/decompals/slinky"

keywords = ["linker_script", "generator", "decompilation", "cli"]
categories = ["development-tools::build-utils", "command-line-utilities"]

[dependencies]
slinky = { path = "../slinky", version = "0.6.0" }
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
